export const FROM_CODE_CHANGE = 'FROM_CODE_CHANGE';
export const FROM_VALUE_CHANGE = 'FROM_VALUE_CHANGE';
export const TO_CODE_CHANGE = 'TO_CODE_CHANGE';
export const TO_VALUE_CHANGE = 'TO_VALUE_CHANGE';
export const RATE_CHANGE = 'RATE_CHANGE';

